<a href="https://colab.research.google.com/github/shreyasat27/MSc-QT-/blob/main/QI_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Define a matrix C
C = np.array([[0, 1/np.sqrt(14)],
              [2/np.sqrt(14), -3/np.sqrt(14)]])

# Perform Singular Value Decomposition
U, singular_values, Vh = np.linalg.svd(C)

# Construct the diagonal matrix D
D = np.zeros_like(C, dtype=float)
np.fill_diagonal(D, singular_values)

# Reconstruct C from U, D, and Vh
C_reconstructed = U @ D @ Vh

# Display results
print("Matrix C:")
print(C)
print("\nMatrix U:")
print(U)
print("\nSingular Values (D matrix):")
print(D)
print("\nMatrix V†:")
print(Vh)
print("\nReconstructed C (U D V†):")
print(C_reconstructed)


Matrix C:
[[ 0.          0.26726124]
 [ 0.53452248 -0.80178373]]

Matrix U:
[[ 0.22975292 -0.97324899]
 [-0.97324899 -0.22975292]]

Singular Values (D matrix):
[[0.98952384 0.        ]
 [0.         0.14436958]]

Matrix V†:
[[-0.52573111  0.85065081]
 [-0.85065081 -0.52573111]]

Reconstructed C (U D V†):
[[ 4.19054524e-17  2.67261242e-01]
 [ 5.34522484e-01 -8.01783726e-01]]


In [4]:
import math

# Given coefficients
a, b, c = 1, -1, 0.140625

# Compute the discriminant
D = b**2 - 4*a*c

# Compute roots
root1 = (-b + math.sqrt(D)) / (2 * a)
root2 = (-b - math.sqrt(D)) / (2 * a)

# Print results
print(f"Roots of the quadratic equation: {root1:.4f}, {root2:.4f}")



Roots of the quadratic equation: 0.8307, 0.1693


In [5]:
!pip install qutip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.1/30.1 MB 35.0 MB/s eta 0:00:00


In [ ]:
import numpy as np
from qutip import *

def is_pure_state(psi):
    # Convert state vector to density matrix if it's a ket
    if psi.type == 'ket':
        rho = psi * psi.dag()  # Outer product to form density matrix
    else:
        rho = psi

    # Compute purity Tr(rho^2)
    purity = (rho * rho).tr()

    return np.isclose(purity, 1), purity

# Example 1: Pure state |0⟩
psi_pure = basis(2, 0)
print(is_pure_state(psi_pure))  # (True, 1.0)

# Example 2: Mixed state ρ = 0.5|0⟩⟨0| + 0.5|1⟩⟨1|
rho_mixed = 0.5 * basis(2, 0) * basis(2, 0).dag() + 0.5 * basis(2, 1) * basis(2, 1).dag()
print(is_pure_state(rho_mixed))  # (False, 0.5)
